# Generated by Django 4.2.4 on 2023-11-05 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_cartid_cart_cid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="cid",
            new_name="cartid",
        ),
    ]
