# Generated by Django 4.2.4 on 2023-11-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_shippingaddress_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="phone_number",
            field=models.BigIntegerField(default=91),
        ),
    ]
