# Generated by Django 4.2.4 on 2023-11-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_order_items_remove_orderitem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paidAt',
            field=models.DateTimeField(null=True),
        ),
    ]
