# Generated by Django 4.2.4 on 2024-01-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_remove_transactions_transid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(default="No Comment"),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
